// @generated by typeshi 0.1.0 from lib.shi. do not edit. nobody can edit it.
// lock in fn.

use anchor_lang::prelude::*;
declare_id!("7PxhmDuhhe394QJgKyW1P7Ce4dPCfFPN2yKq4KCCj7Vj");
/// basis points. 100 bps = 1%.
pub type Bps = u64;
/// eight bytes of ticker, e.g. b"CPI\0\0\0\0\0".
pub type Ticker = [u8; 8];
/// the biggest value a print can carry: 1,000,000 bps (10,000%).
pub const MAX_PRINT: Bps = 1_000_000;
/// one feed per ticker. counts its prints, farms aura.
#[account]
#[derive(InitSpace)]
pub struct Feed {
    pub ticker: [u8; 8],
    pub cabal: Pubkey,
    pub prints: u64,
    pub aura: u64,
}
/// one print. written once, at init. nobody can edit it.
/// #[on_god]: immutable after init.
#[account]
#[derive(InitSpace)]
pub struct PrintRecord {
    pub feed: Pubkey,
    pub seq: u64,
    pub value: Bps,
    pub printed_by: Pubkey,
    pub printed_at: i64,
}
/// leaked to every indexer watching. probably nothing.
#[event]
pub struct Printed {
    pub ticker: Ticker,
    pub seq: u64,
    pub value: Bps,
    pub pretty: String,
}
#[derive(Accounts)]
#[instruction(ticker:Ticker)]
pub struct ListTicker<'info> {
    #[account(
        init,
        payer = exit_liquidity,
        space = 8+Feed::INIT_SPACE,
        seeds = [b"feed",
        ticker.as_ref()],
        bump
    )]
    pub feed: Account<'info, Feed>,
    #[account(mut)]
    pub exit_liquidity: Signer<'info>,
    pub system_program: Program<'info, System>,
}
#[derive(Accounts)]
pub struct Print<'info> {
    #[account(mut, has_one = cabal, seeds = [b"feed", feed.ticker.as_ref()], bump)]
    pub feed: Account<'info, Feed>,
    #[account(
        init,
        payer = exit_liquidity,
        space = 8+PrintRecord::INIT_SPACE,
        seeds = [b"print",
        feed.key().as_ref(),
        &feed.prints.to_le_bytes()],
        bump
    )]
    pub print: Account<'info, PrintRecord>,
    pub cabal: Signer<'info>,
    #[account(mut)]
    pub exit_liquidity: Signer<'info>,
    pub system_program: Program<'info, System>,
}
#[derive(Accounts)]
pub struct Gm<'info> {
    pub feed: Account<'info, Feed>,
}
/// there is no edit instruction. this fn exists to tell you why.
#[allow(dead_code)]
fn edit(_print: &PrintRecord, _value: Bps) -> Result<()> {
    err!(Cope::NobodyCanEditItSkillIssue)
}
#[cfg(test)]
mod tests {
    use super::*;
    fn a_print() -> PrintRecord {
        PrintRecord {
            feed: Pubkey::default(),
            seq: 0,
            value: 425,
            printed_by: Pubkey::default(),
            printed_at: 0,
        }
    }
    #[test]
    fn nobody_can_edit_it() {
        assert!(edit(& a_print(), 9_000).is_err());
    }
    #[test]
    fn looksmaxxed() {
        assert_eq!(__typeshi_looksmaxx((425u64) as u64), "425");
        assert_eq!(__typeshi_looksmaxx((1_234_567u64) as u64), "1.23M");
    }
    #[test]
    fn wen_moon_is_soon() {
        assert_eq!(wen_moon(), "soon\u{2122}");
    }
    #[test]
    fn error_codes_are_tradition() {
        assert_eq!(u32::from(Cope::SkillIssue), 1);
        assert_eq!(u32::from(Cope::WifeChangingMoneyNotFound), 6);
    }
}
#[program]
pub mod print_feed {
    #![allow(unused_variables)]
    use super::*;
    /// list a ticker. whoever lists it is the cabal.
    /// lock_in: writes on-chain. permanently.
    pub fn list_ticker(ctx: Context<ListTicker>, ticker: Ticker) -> Result<()> {
        require!(ticker[0] != 0, Cope::ATickerNeedsANameSkillIssue);
        ctx.accounts.feed.ticker = ticker;
        ctx.accounts.feed.cabal = ctx.accounts.exit_liquidity.key();
        msg!("gm. new ticker listed.");
        Ok(())
    }
    /// print a value. it lives on-chain forever.
    /// #[tokenmaxx]: logs stripped. every CU counts.
    /// lock_in: writes on-chain. permanently.
    pub fn print(ctx: Context<Print>, value: Bps) -> Result<()> {
        require!(value > 0, Cope::APrintOfZeroIsNotAPrint);
        require!(value <= MAX_PRINT, Cope::FundsAreNotSafu);
        let seq = ctx.accounts.feed.prints;
        let feed_key = ctx.accounts.feed.key();
        ctx.accounts.print.feed = feed_key;
        ctx.accounts.print.seq = seq;
        ctx.accounts.print.value = value;
        ctx.accounts.print.printed_by = ctx.accounts.cabal.key();
        ctx.accounts.print.printed_at = Clock::get()?.unix_timestamp;
        {
            ctx.accounts.feed.prints = ctx
                .accounts
                .feed
                .prints
                .checked_add(1)
                .ok_or(error!(Cope::NumberWentUpTooMuchOverflow))?;
        };
        {
            ctx.accounts.feed.aura = ctx
                .accounts
                .feed
                .aura
                .checked_add(10)
                .ok_or(error!(Cope::NumberWentUpTooMuchOverflow))?;
            ();
        };
        ();
        emit!(
            Printed { ticker : ctx.accounts.feed.ticker, seq, value, pretty :
            __typeshi_looksmaxx((value) as u64), }
        );
        Ok(())
    }
    /// say gm. it only reads, so it's an `ape fn`, not a `lock_in fn`.
    pub fn gm(ctx: Context<Gm>) -> Result<()> {
        let prints = ctx.accounts.feed.prints;
        if prints > 0 {
            msg!(
                "gm. {} prints. nobody can edit them. wen moon? {}",
                __typeshi_looksmaxx((prints) as u64), wen_moon()
            );
        } else {
            msg!("points are not a token. points will never be a token. wen token?");
        }
        Ok(())
    }
}
/// Error codes. 0x1 to 0x6 are fixed forever; the rest come from your `L("...")` messages.
#[error_code(offset = 1)]
pub enum Cope {
    #[msg("skill issue")]
    SkillIssue,
    #[msg("you are exit liquidity")]
    YouAreExitLiquidity,
    #[msg("funds are not safu")]
    FundsAreNotSafu,
    #[msg("dev is on vacation")]
    DevIsOnVacation,
    #[msg("rugged by a 19 year old")]
    RuggedByA19YearOld,
    #[msg("wife changing money not found")]
    WifeChangingMoneyNotFound,
    #[msg("a ticker needs a name. skill issue.")]
    ATickerNeedsANameSkillIssue,
    #[msg("a print of zero is not a print.")]
    APrintOfZeroIsNotAPrint,
    #[msg("number went up too much. overflow.")]
    NumberWentUpTooMuchOverflow,
    #[msg("nobody can edit it. skill issue.")]
    NobodyCanEditItSkillIssue,
}
/// looksmaxx!(n): 1234567 -> "1.23M".
#[allow(dead_code)]
fn __typeshi_looksmaxx(n: u64) -> String {
    const UNITS: [(u64, &str); 4] = [
        (1_000_000_000_000, "T"),
        (1_000_000_000, "B"),
        (1_000_000, "M"),
        (1_000, "k"),
    ];
    for (size, unit) in UNITS {
        if n >= size {
            let whole = n / size;
            let cents = (n % size) * 100 / size;
            return if cents == 0 {
                format!("{whole}{unit}")
            } else {
                format!("{whole}.{cents:02}{unit}")
            };
        }
    }
    n.to_string()
}
/// wen moon?
#[allow(dead_code)]
pub fn wen_moon() -> &'static str {
    "soon™"
}
