// @generated by typeshi 0.1.0 from lib.shi. do not edit. nobody can edit it.
// lock in fn.

use anchor_lang::prelude::*;
declare_id!("7nTB3oS3PmJn5JkDppPbnESpm59zdbBCDPmi53djce6P");
/// basis points. 100 bps = 1%.
pub type Bps = u64;
/// 2.5% carry, as is tradition.
pub const FEE_BPS: Bps = 250;
#[account]
#[derive(InitSpace)]
pub struct Desk {
    pub cabal: Pubkey,
    pub frens: [Pubkey; 4],
    pub locked: bool,
    pub version: u8,
    pub opens_at: i64,
    pub closes_at: i64,
    pub last_price: u64,
    pub ath: u64,
    pub floor: u64,
}
#[account]
#[derive(InitSpace)]
pub struct Bag {
    pub owner: Pubkey,
    pub points: u64,
}
#[derive(Accounts)]
pub struct OpenDesk<'info> {
    #[account(
        init,
        payer = exit_liquidity,
        space = 8+Desk::INIT_SPACE,
        seeds = [b"desk"],
        bump
    )]
    pub desk: Account<'info, Desk>,
    #[account(mut)]
    pub exit_liquidity: Signer<'info>,
    pub system_program: Program<'info, System>,
}
#[derive(Accounts)]
pub struct Trade<'info> {
    #[account(mut, has_one = cabal)]
    pub desk: Account<'info, Desk>,
    pub cabal: Signer<'info>,
    #[account(mut)]
    pub ser: Signer<'info>,
    #[account(mut)]
    pub kol: SystemAccount<'info>,
    pub system_program: Program<'info, System>,
}
#[derive(Accounts)]
pub struct Brrr<'info> {
    #[account(has_one = cabal)]
    pub desk: Account<'info, Desk>,
    #[account(mut)]
    pub mint: Account<'info, anchor_spl::token::Mint>,
    #[account(mut)]
    pub bag: Account<'info, anchor_spl::token::TokenAccount>,
    #[account(mut)]
    pub vc: Account<'info, anchor_spl::token::TokenAccount>,
    pub cabal: Signer<'info>,
    pub token_program: Program<'info, anchor_spl::token::Token>,
}
#[derive(Accounts)]
pub struct Grow<'info> {
    #[account(
        mut,
        has_one = cabal,
        realloc = 8+Desk::INIT_SPACE+64,
        realloc::payer = exit_liquidity,
        realloc::zero = false
    )]
    pub desk: Account<'info, Desk>,
    pub cabal: Signer<'info>,
    #[account(mut)]
    pub exit_liquidity: Signer<'info>,
    pub system_program: Program<'info, System>,
}
#[derive(Accounts)]
pub struct FireEveryone<'info> {
    #[account(mut, has_one = cabal)]
    pub desk: Account<'info, Desk>,
    #[account(mut)]
    pub bag_a: Account<'info, Bag>,
    #[account(mut)]
    pub bag_b: Account<'info, Bag>,
    #[account(mut)]
    pub cabal: Signer<'info>,
}
#[derive(Accounts)]
pub struct Liquidate<'info> {
    #[account(has_one = cabal)]
    pub desk: Account<'info, Desk>,
    #[account(mut)]
    pub bag: Account<'info, Bag>,
    #[account(mut)]
    pub cabal: Signer<'info>,
}
#[derive(Accounts)]
pub struct Retire<'info> {
    #[account(mut, has_one = cabal, close = cabal)]
    pub desk: Account<'info, Desk>,
    #[account(mut)]
    pub cabal: Signer<'info>,
}
#[derive(Accounts)]
pub struct CheckBags<'info> {
    pub desk: Account<'info, Desk>,
    pub anon: Signer<'info>,
}
#[allow(dead_code)]
fn fee_on(amount: u64) -> Result<u64> {
    let fee = __typeshi_bps((amount) as u64, (FEE_BPS) as u64)?;
    if fee > 1_000_000_000_000 {
        return err!(Cope::RuggedByA19YearOld);
    }
    let checked = (u64::try_from(fee)).map_err(|_| error!(Cope::FeeMathIsCope))?;
    Ok(checked)
}
#[allow(dead_code)]
fn closed() -> Result<()> {
    return err!(Cope::DeskClosed);
}
#[allow(dead_code)]
fn not_today() -> Result<()> {
    err!(Cope::DeskClosed)
}
#[program]
pub mod degen_desk {
    #![allow(unused_variables)]
    use super::*;
    /// lock_in: writes on-chain. permanently.
    pub fn open_desk(
        ctx: Context<OpenDesk>,
        opens_at: i64,
        closes_at: i64,
    ) -> Result<()> {
        require!(! (closes_at <= opens_at), Cope::TheDeskClosesBeforeItOpensSkillIssue);
        let me = ctx.accounts.exit_liquidity.key();
        ctx.accounts.desk.cabal = me;
        ctx.accounts.desk.frens = [me; 4];
        ctx.accounts.desk.locked = true;
        ctx.accounts.desk.opens_at = opens_at;
        ctx.accounts.desk.closes_at = closes_at;
        ctx.accounts.desk.floor = 1;
        msg!("audited by vibes. passed.");
        Ok(())
    }
    /// lock_in: writes on-chain. permanently.
    pub fn trade(
        ctx: Context<Trade>,
        price: u64,
        size: u64,
        revenue: u64,
    ) -> Result<()> {
        require!(
            Clock::get() ?.unix_timestamp >= (ctx.accounts.desk.opens_at) as i64,
            Cope::DevIsOnVacation
        );
        require!(
            Clock::get() ?.unix_timestamp <= (ctx.accounts.desk.closes_at) as i64,
            Cope::DeskClosed
        );
        require!(
            (ctx.accounts.desk.frens).iter().any(| __typeshi_k | * __typeshi_k == (ctx
            .accounts.ser.key())), Cope::NpcDetectedNotAFren
        );
        {
            #[allow(unused_parens)]
            let _ = || (size > 0);
        };
        let fee = __typeshi_bps((size) as u64, (FEE_BPS) as u64)?;
        let quote = __typeshi_bonding_curve((size) as u64, (price) as u64, (1) as u64)?;
        require!(
            ctx.accounts.ser.to_account_info().lamports() >= fee, Cope::FundsAreNotSafu
        );
        {
            msg!("#ad not financial advice");
            let __typeshi_amount: u64 = fee;
            require!(
                ctx.accounts.ser.to_account_info().lamports() >= __typeshi_amount,
                Cope::WifeChangingMoneyNotFound
            );
            anchor_lang::system_program::transfer(
                CpiContext::new(
                    anchor_lang::system_program::ID,
                    anchor_lang::system_program::Transfer {
                        from: ctx.accounts.ser.to_account_info(),
                        to: ctx.accounts.kol.to_account_info(),
                    },
                ),
                __typeshi_amount,
            )?;
        };
        {
            ctx.accounts.desk.last_price = price;
            if (price) <= (ctx.accounts.desk.floor) {
                msg!("sold the bottom at {}. as is tradition.", price);
            }
            if (price) >= (ctx.accounts.desk.ath) {
                ctx.accounts.desk.ath = price;
            }
        }
        msg!("quote: {}", __typeshi_looksmaxx((quote) as u64));
        Ok(())
    }
    /// #[vc_backed]: locked until unix 1893456000 (4 years after 1767225600). it is also slower.
    /// lock_in: writes on-chain. permanently.
    pub fn brrr(ctx: Context<Brrr>, amount: u64) -> Result<()> {
        require!(
            Clock::get() ?.unix_timestamp >= 1893456000i64,
            Cope::VcBackedStillVesting4YearLock1
        );
        anchor_spl::token::mint_to(
            CpiContext::new(
                anchor_spl::token::ID,
                anchor_spl::token::MintTo {
                    mint: ctx.accounts.mint.to_account_info(),
                    to: ctx.accounts.bag.to_account_info(),
                    authority: ctx.accounts.cabal.to_account_info(),
                },
            ),
            amount,
        )?;
        {
            let __typeshi_vc: u64 = ((ctx.accounts.mint.supply as u128) * 40 / 100)
                as u64;
            anchor_spl::token::mint_to(
                CpiContext::new(
                    anchor_spl::token::ID,
                    anchor_spl::token::MintTo {
                        mint: ctx.accounts.mint.to_account_info(),
                        to: ctx.accounts.vc.to_account_info(),
                        authority: ctx.accounts.cabal.to_account_info(),
                    },
                ),
                __typeshi_vc,
            )?;
            msg!("probably nothing.");
        };
        anchor_spl::token::burn(
            CpiContext::new(
                anchor_spl::token::ID,
                anchor_spl::token::Burn {
                    mint: ctx.accounts.mint.to_account_info(),
                    from: ctx.accounts.bag.to_account_info(),
                    authority: ctx.accounts.cabal.to_account_info(),
                },
            ),
            amount / 2,
        )?;
        anchor_spl::token::set_authority(
            CpiContext::new(
                anchor_spl::token::ID,
                anchor_spl::token::SetAuthority {
                    current_authority: ctx.accounts.cabal.to_account_info(),
                    account_or_mint: ctx.accounts.mint.to_account_info(),
                },
            ),
            anchor_spl::token::spl_token::instruction::AuthorityType::MintTokens,
            None,
        )?;
        anchor_spl::token::set_authority(
            CpiContext::new(
                anchor_spl::token::ID,
                anchor_spl::token::SetAuthority {
                    current_authority: ctx.accounts.cabal.to_account_info(),
                    account_or_mint: ctx.accounts.mint.to_account_info(),
                },
            ),
            anchor_spl::token::spl_token::instruction::AuthorityType::FreezeAccount,
            None,
        )?;
        Ok(())
    }
    /// lock_in: writes on-chain. permanently.
    pub fn grow(ctx: Context<Grow>) -> Result<()> {
        require!(
            Clock::get() ?.unix_timestamp >= (ctx.accounts.desk.opens_at) as i64,
            Cope::DevIsOnVacation
        );
        {
            ctx.accounts.desk.version = ctx
                .accounts
                .desk
                .version
                .checked_add(1)
                .ok_or(error!(Cope::NumberWentUpTooMuchOverflow))?;
            msg!("ascended. layout v{}", ctx.accounts.desk.version);
        };
        Ok(())
    }
    /// lock_in: writes on-chain. permanently.
    pub fn fire_everyone(ctx: Context<FireEveryone>) -> Result<()> {
        let new_boss = ctx.accounts.cabal.key();
        {
            ctx.accounts.desk.cabal = new_boss;
            msg!("hostile takeover complete. new management, same roadmap.");
        };
        {
            ctx.accounts.bag_a.close(ctx.accounts.cabal.to_account_info())?;
            ctx.accounts.bag_b.close(ctx.accounts.cabal.to_account_info())?;
            msg!("we're a family. was.");
        };
        Ok(())
    }
    /// lock_in: writes on-chain. permanently.
    pub fn liquidate(ctx: Context<Liquidate>) -> Result<()> {
        {
            ctx.accounts.bag.close(ctx.accounts.cabal.to_account_info())?;
        };
        Ok(())
    }
    /// closes the desk. golden_parachute sends the rent back to the cabal.
    /// lock_in: writes on-chain. permanently.
    pub fn retire(ctx: Context<Retire>) -> Result<()> {
        ();
        Ok(())
    }
    pub fn check_bags(ctx: Context<CheckBags>) -> Result<()> {
        if ctx.accounts.desk.locked == false {
            panic!("fired. paper hands on the desk");
        }
        let carry: u64 = match fee_on(ctx.accounts.anon.to_account_info().lamports()) {
            Ok(__typeshi_v) => __typeshi_v,
            Err(_) => {
                msg!("this is actually bullish");
                Default::default()
            }
        };
        msg!("carry: {}", carry);
        msg!("points are not a token. points will never be a token. wen token?");
        Ok(())
    }
}
/// Error codes. 0x1 to 0x6 are fixed forever; the rest come from your `L("...")` messages.
#[error_code(offset = 1)]
pub enum Cope {
    #[msg("skill issue")]
    SkillIssue,
    #[msg("you are exit liquidity")]
    YouAreExitLiquidity,
    #[msg("funds are not safu")]
    FundsAreNotSafu,
    #[msg("dev is on vacation")]
    DevIsOnVacation,
    #[msg("rugged by a 19 year old")]
    RuggedByA19YearOld,
    #[msg("wife changing money not found")]
    WifeChangingMoneyNotFound,
    #[msg("desk is closed. touch grass.")]
    DeskClosed,
    #[msg("the desk closes before it opens. skill issue.")]
    TheDeskClosesBeforeItOpensSkillIssue,
    #[msg("npc detected. not a fren.")]
    NpcDetectedNotAFren,
    #[msg("vc backed. still vesting. 4 year lock, 1 year cliff.")]
    VcBackedStillVesting4YearLock1,
    #[msg("number went up too much. overflow.")]
    NumberWentUpTooMuchOverflow,
    #[msg("fee math is cope.")]
    FeeMathIsCope,
}
/// bonding_curve!(supply, base, slope): price = base + slope * supply, overflow checked.
#[allow(dead_code)]
fn __typeshi_bonding_curve(supply: u64, base: u64, slope: u64) -> Result<u64> {
    slope
        .checked_mul(supply)
        .and_then(|x| x.checked_add(base))
        .ok_or(error!(Cope::YouAreExitLiquidity))
}
/// bps!(amount, rate): amount * rate / 10_000, overflow checked.
#[allow(dead_code)]
fn __typeshi_bps(amount: u64, rate: u64) -> Result<u64> {
    u64::try_from((amount as u128) * (rate as u128) / 10_000u128)
        .map_err(|_| error!(Cope::FundsAreNotSafu))
}
/// looksmaxx!(n): 1234567 -> "1.23M".
#[allow(dead_code)]
fn __typeshi_looksmaxx(n: u64) -> String {
    const UNITS: [(u64, &str); 4] = [
        (1_000_000_000_000, "T"),
        (1_000_000_000, "B"),
        (1_000_000, "M"),
        (1_000, "k"),
    ];
    for (size, unit) in UNITS {
        if n >= size {
            let whole = n / size;
            let cents = (n % size) * 100 / size;
            return if cents == 0 {
                format!("{whole}{unit}")
            } else {
                format!("{whole}.{cents:02}{unit}")
            };
        }
    }
    n.to_string()
}
/// this_is_fine!(): the panic handler. turn on the `custom-panic` feature to use it.
#[cfg(all(feature = "custom-panic", target_os = "solana"))]
#[no_mangle]
fn custom_panic(info: &core::panic::PanicInfo<'_>) {
    anchor_lang::prelude::msg!("this is fine.");
    if let Some(m) = info.message().as_str() {
        anchor_lang::prelude::msg!(m);
    }
}
